spring.application.name=bloodmood
server.port=3001



#postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/bloommood
spring.datasource.username=bloommood
spring.datasource.password=bloommood123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
